services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: phpmon-web
    depends_on:
      - db
    environment:
      APP_URL: ${APP_URL:-http://localhost:8080}
      APP_NAME: ${APP_NAME:-My App}
      APP_DESC: ${APP_DESC:-Default edit me}
      DEBUG_MODE: ${DEBUG_MODE:-true}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-phpmon}
      DB_USER: ${DB_USER:-phpmon}
      DB_PASS: ${DB_PASS:-phpmon}
    ports:
      - "8080:80"

  db:
    image: mariadb:11.4
    container_name: phpmon-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME:-phpmon}
      MARIADB_USER: ${DB_USER:-phpmon}
      MARIADB_PASSWORD: ${DB_PASS:-phpmon}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
