<?php

$dbName = getenv('DB_NAME') ?: 'phpmon';
$dbHost = getenv('DB_HOST') ?: '127.0.0.1';
$dbPort = getenv('DB_PORT') ?: '3306';
$dbUser = getenv('DB_USER') ?: 'root';
$dbPass = getenv('DB_PASS') ?: '';

$appUrl = getenv('APP_URL') ?: 'http://localhost:8080';
$appName = getenv('APP_NAME') ?: 'My Sandbox';
$appDesc = getenv('APP_DESC') ?: 'Default edit me';
$debugMode = filter_var(getenv('DEBUG_MODE') ?: 'true', FILTER_VALIDATE_BOOLEAN);
$ticketAutoCloseDays = (int)(getenv('TICKET_AUTO_CLOSE_DAYS') ?: 14);
$ldapEnabled = filter_var(getenv('LDAP_ENABLED') ?: 'false', FILTER_VALIDATE_BOOLEAN);
$ldapHost = trim((string)(getenv('LDAP_HOST') ?: ''));
$ldapPort = (int)(getenv('LDAP_PORT') ?: 636);
$ldapBaseDn = trim((string)(getenv('LDAP_BASE_DN') ?: ''));
$ldapUsername = trim((string)(getenv('LDAP_USERNAME') ?: ''));
$ldapPassword = (string)(getenv('LDAP_PASSWORD') ?: '');
$ldapUseSsl = filter_var(getenv('LDAP_USE_SSL') ?: 'true', FILTER_VALIDATE_BOOLEAN);
$ldapUseTls = filter_var(getenv('LDAP_USE_TLS') ?: 'false', FILTER_VALIDATE_BOOLEAN);
$ldapTimeout = (int)(getenv('LDAP_TIMEOUT') ?: 5);
$ldapDomain = trim((string)(getenv('LDAP_DOMAIN') ?: ''));
$ldapUserFilterAttribute = trim((string)(getenv('LDAP_USER_FILTER_ATTRIBUTE') ?: 'samaccountname'));
$ldapTlsRequireCert = filter_var(getenv('LDAP_TLS_REQUIRE_CERT') ?: 'true', FILTER_VALIDATE_BOOLEAN);
$mailerDsn = trim((string)(getenv('MAILER_DSN') ?: ''));
$mailFromAddress = trim((string)(getenv('MAIL_FROM_ADDRESS') ?: ''));
$mailFromName = trim((string)(getenv('MAIL_FROM_NAME') ?: $appName));
$mailEnabled = filter_var(getenv('MAIL_ENABLED') ?: ($mailerDsn !== '' && $mailFromAddress !== '' ? 'true' : 'false'), FILTER_VALIDATE_BOOLEAN);
$inboundMailAddress = trim((string)(getenv('INBOUND_MAIL_ADDRESS') ?: $mailFromAddress));
$inboundMailPlusAddressingEnabled = filter_var(getenv('INBOUND_MAIL_PLUS_ADDRESSING_ENABLED') ?: 'false', FILTER_VALIDATE_BOOLEAN);
$inboundMailPlusDelimiter = trim((string)(getenv('INBOUND_MAIL_PLUS_DELIMITER') ?: '+'));
$inboundMailEnabled = filter_var(getenv('INBOUND_MAIL_ENABLED') ?: 'false', FILTER_VALIDATE_BOOLEAN);
$inboundMailDriver = strtolower(trim((string)(getenv('INBOUND_MAIL_DRIVER') ?: 'imap')));
$inboundImapHost = trim((string)(getenv('INBOUND_IMAP_HOST') ?: ''));
$inboundImapPort = (int)(getenv('INBOUND_IMAP_PORT') ?: 993);
$inboundImapEncryption = strtolower(trim((string)(getenv('INBOUND_IMAP_ENCRYPTION') ?: 'ssl')));
$inboundImapUsername = trim((string)(getenv('INBOUND_IMAP_USERNAME') ?: ''));
$inboundImapPassword = (string)(getenv('INBOUND_IMAP_PASSWORD') ?: '');
$inboundImapMailbox = trim((string)(getenv('INBOUND_IMAP_MAILBOX') ?: 'INBOX'));
$inboundImapProcessedMailbox = trim((string)(getenv('INBOUND_IMAP_PROCESSED_MAILBOX') ?: 'Processed'));
$inboundImapFailedMailbox = trim((string)(getenv('INBOUND_IMAP_FAILED_MAILBOX') ?: 'Failed'));
$inboundImapValidateCert = filter_var(getenv('INBOUND_IMAP_VALIDATE_CERT') ?: 'true', FILTER_VALIDATE_BOOLEAN);
$inboundImapMaxMessages = (int)(getenv('INBOUND_IMAP_MAX_MESSAGES') ?: 25);

define('DBNAME', $dbName);
define('DBHOST', $dbHost);
define('DBPORT', $dbPort);
define('DBUSER', $dbUser);
define('DBPASS', $dbPass);

define('ROOT', rtrim($appUrl, '/'));

define('APP_NAME', $appName);
define('APP_DESC', $appDesc);

define('DEBUG_MODE', $debugMode);
define('TICKET_AUTO_CLOSE_DAYS', max(1, $ticketAutoCloseDays));
define('LDAP_ENABLED', $ldapEnabled);
define('LDAP_HOST', $ldapHost);
define('LDAP_PORT', $ldapPort > 0 ? $ldapPort : 636);
define('LDAP_BASE_DN', $ldapBaseDn);
define('LDAP_USERNAME', $ldapUsername);
define('LDAP_PASSWORD', $ldapPassword);
define('LDAP_USE_SSL', $ldapUseSsl);
define('LDAP_USE_TLS', $ldapUseTls);
define('LDAP_TIMEOUT', max(1, $ldapTimeout));
define('LDAP_DOMAIN', $ldapDomain);
define('LDAP_USER_FILTER_ATTRIBUTE', preg_match('/^[a-zA-Z][a-zA-Z0-9-]*$/', $ldapUserFilterAttribute) ? $ldapUserFilterAttribute : 'samaccountname');
define('LDAP_TLS_REQUIRE_CERT', $ldapTlsRequireCert);
define('MAIL_ENABLED', $mailEnabled);
define('MAILER_DSN', $mailerDsn);
define('MAIL_FROM_ADDRESS', $mailFromAddress);
define('MAIL_FROM_NAME', $mailFromName);
define('INBOUND_MAIL_ADDRESS', $inboundMailAddress);
define('INBOUND_MAIL_PLUS_ADDRESSING_ENABLED', $inboundMailPlusAddressingEnabled);
define('INBOUND_MAIL_PLUS_DELIMITER', preg_match('/^[+._-]$/', $inboundMailPlusDelimiter) ? $inboundMailPlusDelimiter : '+');
define('INBOUND_MAIL_ENABLED', $inboundMailEnabled);
define('INBOUND_MAIL_DRIVER', in_array($inboundMailDriver, ['imap'], true) ? $inboundMailDriver : 'imap');
define('INBOUND_IMAP_HOST', $inboundImapHost);
define('INBOUND_IMAP_PORT', $inboundImapPort > 0 ? $inboundImapPort : 993);
define('INBOUND_IMAP_ENCRYPTION', in_array($inboundImapEncryption, ['ssl', 'tls', 'none'], true) ? $inboundImapEncryption : 'ssl');
define('INBOUND_IMAP_USERNAME', $inboundImapUsername);
define('INBOUND_IMAP_PASSWORD', $inboundImapPassword);
define('INBOUND_IMAP_MAILBOX', $inboundImapMailbox !== '' ? $inboundImapMailbox : 'INBOX');
define('INBOUND_IMAP_PROCESSED_MAILBOX', $inboundImapProcessedMailbox);
define('INBOUND_IMAP_FAILED_MAILBOX', $inboundImapFailedMailbox);
define('INBOUND_IMAP_VALIDATE_CERT', $inboundImapValidateCert);
define('INBOUND_IMAP_MAX_MESSAGES', max(1, min(250, $inboundImapMaxMessages)));
